server:
  port: 8002
  servlet:
    session:
      cookie:
        domain: localhost


spring:
  datasource:
    username: root
    password: Lykin172855.
    url: jdbc:mysql://127.0.0.1:3306/letty?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
#    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
#session失效时间
  session:
    timeout: 86400






  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Lykin172855.





mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.letty.usercenter.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
